---
resources:
- name: app
  type: git
  source:
    uri: https://github.com/mdramos/spring-music.git
    branch: master

- name: deploy-web-app
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-organization))
    space: ((cf-space))
    skip_cert_check: true

jobs:
- name: deploy-app
  public: true
  serial: true
  plan:
  - get: app
    trigger: true
  - task: app-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: java, tag: openjdk-8-alpine}
      inputs:
      - name: app
      run:
        path: app/test-main.sh
  - task: app-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: java, tag: openjdk-8-alpine}
      inputs:
      - name: app
      run:
        path: app/build-main.sh

  - put: deploy-web-app
    params:
      manifest: app/manifest.yml
      path: app